version: '3.8'

networks:
  note-easy:


services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: test
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - note-easy

  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      DB_HOST: mysql
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: test
      DB_PORT: 3306
    depends_on:
      - mysql
    networks:
      - note-easy
volumes:
  my-db:
